#!/usr/bin/env bash
set -Eeuo pipefail

SERVICE_NAME="nachopanel"
INSTALL_ROOT="/opt/nachopanel"
DATA_DIR="/var/lib/nachopanel"
CONFIG_DIR="/etc/nachopanel"
ENV_FILE="$CONFIG_DIR/nachopanel.env"
UNIT_FILE="/etc/systemd/system/$SERVICE_NAME.service"
NODE_VERSION="${NACHO_NODE_VERSION:-22.17.0}"
VERSION="${NACHO_VERSION:-3.0.0}"
REPOSITORY="${NACHO_GITHUB_REPOSITORY:-nachomao/nachopanel-deploy}"
NODE_VERSION_SET=$([[ -n "${NACHO_NODE_VERSION:-}" ]] && printf 1 || printf 0)
VERSION_SET=$([[ -n "${NACHO_VERSION:-}" ]] && printf 1 || printf 0)
REPOSITORY_SET=$([[ -n "${NACHO_GITHUB_REPOSITORY:-}" ]] && printf 1 || printf 0)
PUBLIC_URL="${NACHO_PUBLIC_URL:-}"
INSTALLER_PUBLIC_URL="${NACHO_INSTALLER_PUBLIC_URL:-}"
AGENT_AUTH_MODE="${NACHO_AGENT_AUTH_MODE:-required}"
AGENT_AUTH_MODE_SET=$([[ -n "${NACHO_AGENT_AUTH_MODE:-}" ]] && printf 1 || printf 0)
AGENT_AUTH_CONFIRMED=$([[ "${NACHO_CONFIRM_UNAUTHENTICATED_AGENTS:-}" == "1" ]] && printf 1 || printf 0)
DATABASE_VALUE="${DATABASE_URL:-}"
DATABASE_FILE=""
ALLOW_HTTP=0
PURGE=0
ACTION="${1:-install}"
PREVIOUS_RELEASE=""
NEW_RELEASE=""
SWITCHED=0
BOOTSTRAP_SECRET=""
CONFIG_LOADED=0

if [[ $# -gt 0 ]]; then shift; fi

log() { printf '[NachoPanel] %s\n' "$*"; }
fail() { printf '[NachoPanel] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: install.sh <install|upgrade|repair|status|uninstall> [options]

Options:
  --version VERSION             Release version (default: 3.0.0)
  --repository OWNER/REPO       Override the GitHub repository containing release assets
  --public-url URL              Public HTTPS origin for NachoPanel
  --installer-public-url URL    Optional public HTTPS origin for the 8090 gateway
  --disable-agent-auth          Allow clients without credentials (security risk)
  --require-agent-auth          Require enrollment and per-client credentials
  --database-url-file PATH      Root-readable file containing DATABASE_URL
  --allow-http                  Permit an HTTP public URL for private testing
  --purge                       Remove config and local artifacts on uninstall
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) VERSION="${2:?missing version}"; VERSION_SET=1; shift 2 ;;
    --repository) REPOSITORY="${2:?missing repository}"; REPOSITORY_SET=1; shift 2 ;;
    --public-url) PUBLIC_URL="${2:?missing public URL}"; shift 2 ;;
    --installer-public-url) INSTALLER_PUBLIC_URL="${2:?missing installer public URL}"; shift 2 ;;
    --disable-agent-auth) AGENT_AUTH_MODE="disabled"; AGENT_AUTH_MODE_SET=1; AGENT_AUTH_CONFIRMED=1; shift ;;
    --require-agent-auth) AGENT_AUTH_MODE="required"; AGENT_AUTH_MODE_SET=1; shift ;;
    --database-url-file) DATABASE_FILE="${2:?missing database URL file}"; shift 2 ;;
    --allow-http) ALLOW_HTTP=1; shift ;;
    --purge) PURGE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

require_root() { [[ ${EUID:-$(id -u)} -eq 0 ]] || fail "Run this command as root"; }
require_command() { command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"; }

load_existing_config() {
  if [[ -f "$ENV_FILE" ]]; then
    CONFIG_LOADED=1
    local requested_database="$DATABASE_VALUE" requested_public="$PUBLIC_URL" requested_installer_public="$INSTALLER_PUBLIC_URL"
    local requested_repository="$REPOSITORY" requested_version="$VERSION" requested_node_version="$NODE_VERSION" requested_agent_auth="$AGENT_AUTH_MODE"
    set -a
    # The file is root-owned and generated by this installer.
    source "$ENV_FILE"
    set +a
    DATABASE_VALUE="${requested_database:-${DATABASE_URL:-}}"
    PUBLIC_URL="${requested_public:-${NACHO_PUBLIC_URL:-}}"
    INSTALLER_PUBLIC_URL="${requested_installer_public:-${NACHO_INSTALLER_PUBLIC_URL:-}}"
    if [[ $REPOSITORY_SET -eq 0 ]]; then REPOSITORY="${NACHO_GITHUB_REPOSITORY:-$requested_repository}"; fi
    if [[ $VERSION_SET -eq 0 ]]; then VERSION="${NACHO_VERSION:-$requested_version}"; fi
    if [[ $NODE_VERSION_SET -eq 0 ]]; then NODE_VERSION="${NACHO_NODE_VERSION:-$requested_node_version}"; fi
    if [[ $AGENT_AUTH_MODE_SET -eq 0 ]]; then AGENT_AUTH_MODE="${NACHO_AGENT_AUTH_MODE:-$requested_agent_auth}"; fi
  fi
}

validate_platform() {
  [[ -r /etc/os-release ]] || fail "Cannot identify this Linux distribution"
  # shellcheck disable=SC1091
  source /etc/os-release
  case "${ID:-}" in
    ubuntu)
      [[ "${VERSION_ID:-}" == "22.04" || "${VERSION_ID:-}" == "24.04" ]] || fail "Supported Ubuntu versions are 22.04 and 24.04"
      ;;
    debian)
      [[ "${VERSION_ID:-}" == "12" ]] || fail "Supported Debian version is 12"
      ;;
    *) fail "Supported distributions are Ubuntu 22.04/24.04 and Debian 12" ;;
  esac
  [[ -d /run/systemd/system ]] || fail "systemd must be running as the service manager"
  [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9.-]+)?$ ]] || fail "Invalid NachoPanel release version: $VERSION"
  [[ "$NODE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "Invalid Node.js version: $NODE_VERSION"
  [[ "$AGENT_AUTH_MODE" == "required" || "$AGENT_AUTH_MODE" == "disabled" ]] || fail "NACHO_AGENT_AUTH_MODE must be required or disabled"
  if [[ "$AGENT_AUTH_MODE" == "disabled" ]]; then
    [[ $CONFIG_LOADED -eq 1 || $AGENT_AUTH_CONFIRMED -eq 1 ]] || fail "Disabling agent authentication requires --disable-agent-auth or NACHO_CONFIRM_UNAUTHENTICATED_AGENTS=1"
    log "WARNING: agent authentication is disabled; anyone who can reach the API can impersonate a client"
  fi
}

ensure_dependencies() {
  local missing=0
  for command in curl tar xz sha256sum awk sed grep find sort getent groupadd useradd systemctl journalctl; do
    if ! command -v "$command" >/dev/null 2>&1; then missing=1; break; fi
  done
  if [[ $missing -eq 1 ]]; then
    require_command apt-get
    log "Installing required operating-system packages"
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl tar xz-utils coreutils findutils gawk sed grep passwd libc-bin systemd
  fi
  for command in curl tar xz sha256sum awk sed grep find sort getent groupadd useradd systemctl journalctl; do require_command "$command"; done
}

read_required_values() {
  load_existing_config
  if [[ -n "$DATABASE_FILE" ]]; then
    [[ -r "$DATABASE_FILE" ]] || fail "Cannot read database URL file"
    DATABASE_VALUE=$(tr -d '\r\n' < "$DATABASE_FILE")
  fi
  if [[ -z "$DATABASE_VALUE" && -r /dev/tty ]]; then
    read -r -s -p "PostgreSQL DATABASE_URL: " DATABASE_VALUE </dev/tty
    printf '\n' >/dev/tty
  fi
  [[ "$DATABASE_VALUE" == postgresql://* || "$DATABASE_VALUE" == postgres://* ]] || fail "A PostgreSQL DATABASE_URL is required"
  if [[ -z "$PUBLIC_URL" && -r /dev/tty ]]; then
    read -r -p "Public NachoPanel URL (https://panel.example.com): " PUBLIC_URL </dev/tty
  fi
  PUBLIC_URL="${PUBLIC_URL%/}"
  [[ "$DATABASE_VALUE" != *$'\n'* && "$DATABASE_VALUE" != *$'\r'* ]] || fail "DATABASE_URL must be a single line"
  [[ "$PUBLIC_URL" != *$'\n'* && "$PUBLIC_URL" != *$'\r'* ]] || fail "Public URL must be a single line"
  if [[ $ALLOW_HTTP -eq 1 ]]; then
    [[ "$PUBLIC_URL" =~ ^https?://(\[[0-9A-Fa-f:]+\]|[A-Za-z0-9.-]+)(:[0-9]{1,5})?$ ]] || fail "Public URL must be an HTTP/HTTPS origin without a path"
  else
    [[ "$PUBLIC_URL" =~ ^https://(\[[0-9A-Fa-f:]+\]|[A-Za-z0-9.-]+)(:[0-9]{1,5})?$ ]] || fail "Public URL must be an HTTPS origin without a path (or pass --allow-http for private testing)"
  fi
  if [[ -n "$INSTALLER_PUBLIC_URL" ]]; then
    INSTALLER_PUBLIC_URL="${INSTALLER_PUBLIC_URL%/}"
    [[ "$INSTALLER_PUBLIC_URL" != *$'\n'* && "$INSTALLER_PUBLIC_URL" != *$'\r'* ]] || fail "Installer public URL must be a single line"
    if [[ $ALLOW_HTTP -eq 1 ]]; then
      [[ "$INSTALLER_PUBLIC_URL" =~ ^https?://(\[[0-9A-Fa-f:]+\]|[A-Za-z0-9.-]+)(:[0-9]{1,5})?$ ]] || fail "Installer public URL must be an HTTP/HTTPS origin without a path"
    else
      [[ "$INSTALLER_PUBLIC_URL" =~ ^https://(\[[0-9A-Fa-f:]+\]|[A-Za-z0-9.-]+)(:[0-9]{1,5})?$ ]] || fail "Installer public URL must be an HTTPS origin without a path"
    fi
  fi
  [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9.-]+)?$ ]] || fail "Invalid NachoPanel release version: $VERSION"
  [[ "$NODE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "Invalid Node.js version: $NODE_VERSION"
}

escape_env() {
  local value="$1"
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || fail "Environment values must be a single line"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$/\\\$}
  value=${value//\`/\\\`}
  printf '%s' "$value"
}

write_config() {
  install -d -m 0750 -o root -g nachopanel "$CONFIG_DIR"
  local temporary
  temporary=$(mktemp "$CONFIG_DIR/.nachopanel.env.XXXXXX")
  cat > "$temporary" <<EOF
NODE_ENV="production"
NACHO_VERSION="$(escape_env "$VERSION")"
NACHO_NODE_VERSION="$(escape_env "$NODE_VERSION")"
NACHO_GITHUB_REPOSITORY="$(escape_env "$REPOSITORY")"
PORT="${PORT:-3000}"
INSTALLER_PORT="${INSTALLER_PORT:-8090}"
NACHO_PUBLIC_URL="$(escape_env "$PUBLIC_URL")"
NACHO_AGENT_AUTH_MODE="$(escape_env "$AGENT_AUTH_MODE")"
DATABASE_URL="$(escape_env "$DATABASE_VALUE")"
NACHO_DATA_DIR="$(escape_env "$DATA_DIR")"
NACHO_ARTIFACT_DIR="$(escape_env "$DATA_DIR/artifacts")"
EOF
  if [[ -n "$INSTALLER_PUBLIC_URL" ]]; then printf 'NACHO_INSTALLER_PUBLIC_URL="%s"\n' "$(escape_env "$INSTALLER_PUBLIC_URL")" >> "$temporary"; fi
  for name in NACHO_S3_BUCKET NACHO_S3_REGION NACHO_S3_ENDPOINT NACHO_S3_PATH_STYLE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN INSTALLER_GATEWAY_DISABLED; do
    if [[ -n "${!name:-}" ]]; then printf '%s="%s"\n' "$name" "$(escape_env "${!name}")" >> "$temporary"; fi
  done
  chmod 0600 "$temporary"
  chown root:root "$temporary"
  mv -f "$temporary" "$ENV_FILE"
}

install_node_runtime() {
  local machine node_arch archive base expected actual staging
  machine=$(uname -m)
  case "$machine" in
    x86_64|amd64) node_arch="x64" ;;
    aarch64|arm64) node_arch="arm64" ;;
    *) fail "Unsupported architecture: $machine" ;;
  esac
  if [[ -x "$INSTALL_ROOT/runtime/node/bin/node" ]] && [[ "$($INSTALL_ROOT/runtime/node/bin/node --version)" == "v$NODE_VERSION" ]]; then return; fi
  archive="node-v$NODE_VERSION-linux-$node_arch.tar.xz"
  base="https://nodejs.org/dist/v$NODE_VERSION"
  staging=$(mktemp -d)
  curl -fsSL "$base/$archive" -o "$staging/$archive"
  curl -fsSL "$base/SHASUMS256.txt" -o "$staging/SHASUMS256.txt"
  expected=$(awk -v file="$archive" '$2 == file { print $1; exit }' "$staging/SHASUMS256.txt")
  [[ -n "$expected" ]] || fail "Node.js checksum not found"
  actual=$(sha256sum "$staging/$archive" | awk '{print $1}')
  [[ "$actual" == "$expected" ]] || fail "Node.js checksum verification failed"
  rm -rf "$INSTALL_ROOT/runtime/node-v$NODE_VERSION" "$INSTALL_ROOT/runtime/node.new"
  mkdir -p "$INSTALL_ROOT/runtime/node-v$NODE_VERSION"
  tar -xJf "$staging/$archive" -C "$INSTALL_ROOT/runtime/node-v$NODE_VERSION" --strip-components=1
  ln -s "$INSTALL_ROOT/runtime/node-v$NODE_VERSION" "$INSTALL_ROOT/runtime/node.new"
  mv -Tf "$INSTALL_ROOT/runtime/node.new" "$INSTALL_ROOT/runtime/node"
  rm -rf "$staging"
}

download_release() {
  [[ "$REPOSITORY" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || fail "Invalid GitHub repository; use --repository OWNER/REPO"
  local base archive checksum staging expected actual unpack
  base="https://github.com/$REPOSITORY/releases/download/v$VERSION"
  archive="nachopanel-$VERSION.tar.gz"
  checksum="$archive.sha256"
  staging=$(mktemp -d)
  log "Downloading NachoPanel $VERSION from $REPOSITORY"
  curl -fsSL "$base/$archive" -o "$staging/$archive"
  curl -fsSL "$base/$checksum" -o "$staging/$checksum"
  expected=$(awk '{print $1; exit}' "$staging/$checksum")
  actual=$(sha256sum "$staging/$archive" | awk '{print $1}')
  [[ -n "$expected" && "$actual" == "$expected" ]] || fail "NachoPanel release checksum verification failed"
  NEW_RELEASE="$INSTALL_ROOT/releases/$VERSION-$(date -u +%Y%m%d%H%M%S)-$$"
  unpack="$INSTALL_ROOT/releases/.staging-$VERSION-$$"
  rm -rf "$unpack"
  mkdir -p "$unpack"
  tar -xzf "$staging/$archive" -C "$unpack" --strip-components=1
  [[ -f "$unpack/server/host.mjs" && -f "$unpack/app/server.js" ]] || fail "Release archive is incomplete"
  mv "$unpack" "$NEW_RELEASE"
  chown -R root:nachopanel "$NEW_RELEASE"
  chmod -R u=rwX,g=rX,o= "$NEW_RELEASE"
  rm -rf "$staging"
}

rollback() {
  local code=$?
  trap - ERR
  if [[ $SWITCHED -eq 1 && -n "$PREVIOUS_RELEASE" && -d "$PREVIOUS_RELEASE" ]]; then
    log "Deployment failed; restoring $(basename "$PREVIOUS_RELEASE")"
    ln -s "$PREVIOUS_RELEASE" "$INSTALL_ROOT/current.rollback"
    mv -Tf "$INSTALL_ROOT/current.rollback" "$INSTALL_ROOT/current"
    systemctl daemon-reload || true
    systemctl restart "$SERVICE_NAME" || true
  elif [[ $SWITCHED -eq 1 ]]; then
    systemctl stop "$SERVICE_NAME" || true
    rm -f "$INSTALL_ROOT/current"
  fi
  exit "$code"
}

activate_release() {
  PREVIOUS_RELEASE=$(readlink -f "$INSTALL_ROOT/current" 2>/dev/null || true)
  ln -s "$NEW_RELEASE" "$INSTALL_ROOT/current.new"
  mv -Tf "$INSTALL_ROOT/current.new" "$INSTALL_ROOT/current"
  SWITCHED=1
}

run_migrations() {
  export DATABASE_URL="$DATABASE_VALUE" NACHO_PROJECT_ROOT="$NEW_RELEASE" NACHO_VERSION="$VERSION"
  "$INSTALL_ROOT/runtime/node/bin/node" "$NEW_RELEASE/server/migrate.mjs"
}

bootstrap_key() {
  export DATABASE_URL="$DATABASE_VALUE" NACHO_PROJECT_ROOT="$NEW_RELEASE" NACHO_VERSION="$VERSION"
  local result
  result=$("$INSTALL_ROOT/runtime/node/bin/node" "$NEW_RELEASE/server/admin-cli.mjs" key bootstrap --json)
  BOOTSTRAP_SECRET=$(printf '%s' "$result" | sed -n 's/.*"secret":"\([^"]*\)".*/\1/p')
}

wait_for_health() {
  local port="${PORT:-3000}" response attempt
  for ((attempt=1; attempt<=45; attempt++)); do
    if response=$(curl -fsS "http://127.0.0.1:$port/api/v1/health" 2>/dev/null) && printf '%s' "$response" | grep -q '"status":"ready"'; then return 0; fi
    sleep 1
  done
  journalctl -u "$SERVICE_NAME" -n 50 --no-pager >&2 || true
  return 1
}

cleanup_old_releases() {
  local current candidate line kept=0
  current=$(readlink -f "$INSTALL_ROOT/current" 2>/dev/null || true)
  while IFS= read -r line; do
    candidate=${line#* }
    [[ -n "$candidate" && -d "$candidate" ]] || continue
    if [[ "$candidate" == "$current" ]]; then continue; fi
    kept=$((kept + 1))
    if [[ $kept -gt 2 ]]; then rm -rf -- "$candidate"; fi
  done < <(find "$INSTALL_ROOT/releases" -mindepth 1 -maxdepth 1 -type d ! -name '.staging-*' -printf '%T@ %p\n' | sort -rn)
}

install_or_upgrade() {
  require_root
  validate_platform
  ensure_dependencies
  read_required_values
  getent group nachopanel >/dev/null || groupadd --system nachopanel
  id -u nachopanel >/dev/null 2>&1 || useradd --system --gid nachopanel --home-dir "$DATA_DIR" --shell /usr/sbin/nologin nachopanel
  install -d -m 0750 -o root -g nachopanel "$INSTALL_ROOT" "$INSTALL_ROOT/releases" "$INSTALL_ROOT/runtime"
  install -d -m 0750 -o nachopanel -g nachopanel "$DATA_DIR" "$DATA_DIR/artifacts"
  install_node_runtime
  download_release
  write_config
  run_migrations
  activate_release
  install -m 0644 "$NEW_RELEASE/deploy/nachopanel.service" "$UNIT_FILE"
  systemctl daemon-reload
  systemctl enable "$SERVICE_NAME" >/dev/null
  systemctl restart "$SERVICE_NAME"
  wait_for_health
  install -m 0750 "$NEW_RELEASE/deploy/install.sh" /usr/local/sbin/nachopanelctl
  cleanup_old_releases || log "Warning: old release cleanup did not complete"
  bootstrap_key
  log "NachoPanel $VERSION is ready at $PUBLIC_URL"
  if [[ -n "$BOOTSTRAP_SECRET" ]]; then
    printf '\nAdministrator API Key (shown once):\n%s\n\n' "$BOOTSTRAP_SECRET"
  else
    log "An active administrator API Key already exists; no new key was created"
  fi
  SWITCHED=0
  log "Status: systemctl status $SERVICE_NAME"
  log "Manage: nachopanelctl <status|repair|upgrade|uninstall>"
}

show_status() {
  require_root
  load_existing_config
  systemctl status "$SERVICE_NAME" --no-pager || true
  if [[ -L "$INSTALL_ROOT/current" ]]; then log "Installed release: $(basename "$(readlink -f "$INSTALL_ROOT/current")")"; fi
  curl -fsS "http://127.0.0.1:${PORT:-3000}/api/v1/health" || true
  printf '\n'
}

uninstall_service() {
  require_root
  systemctl disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
  rm -f "$UNIT_FILE"
  rm -f /usr/local/sbin/nachopanelctl
  systemctl daemon-reload
  rm -rf "$INSTALL_ROOT"
  if [[ $PURGE -eq 1 ]]; then
    rm -rf "$CONFIG_DIR" "$DATA_DIR"
    userdel nachopanel >/dev/null 2>&1 || true
    groupdel nachopanel >/dev/null 2>&1 || true
    log "Service, configuration, and local artifacts removed; the PostgreSQL database was not dropped"
  else
    log "Service removed; configuration and local artifacts were preserved"
  fi
}

trap rollback ERR
case "$ACTION" in
  install|upgrade|repair) install_or_upgrade ;;
  status) show_status ;;
  uninstall) uninstall_service ;;
  *) usage; exit 2 ;;
esac
